### ISSUE TITLE
Circular curly brace detection can have recursive loop

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-javascript#206]
We need to reimplement, detection with simplified messages and early exit.

**Comment by happy5214** [comment]
Isn't recursion already dealt with? We have several tests in BIDS sidecar group `sub07` dedicated to this issue, including mutual recursion, self-recursion, and multi-level nesting. What is actually not working?

**Comment by VisLab** [comment]
Look at the error message for "/sub07/sub07_task-test_run-9_events.json"   in the "Curly braces" test in `bids.spec.js`

**Comment by happy5214** [comment]
I assume this is related to #205, because the tests on `master` related to curly braces pass. It's actually run *10* that's failing, and that's because you forgot to update the `emptyCurlyBrace` issue on lines 613-618 of `bids.spec.js` to reflect the fact that the index is now passed as a parameter to `generateIssue` by the tokenizer.

**Comment by VisLab** [comment]
Okay.... will consider collective error message later.
